name: repo-sync

on:
  schedule:
  - cron:  "* */1 * * *"
  push:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repos_list:
# Minecraft server
        - { source: "git@github.com:itzg/mc-monitor.git", destination: "git@github.com:Bensuperpc/mc-monitor.git" }
        - { source: "git@github.com:itzg/docker-minecraft-server.git", destination: "git@github.com:Bensuperpc/docker-minecraft-server-1.git" }
        - { source: "git@github.com:itzg/docker-rcon-web-admin.git", destination: "git@github.com:Bensuperpc/docker-rcon-web-admin.git" }
        - { source: "git@github.com:itzg/docker-mc-backup.git", destination: "git@github.com:Bensuperpc/docker-mc-backup.git" }
        - { source: "git@github.com:itzg/docker-bungeecord.git", destination: "git@github.com:Bensuperpc/docker-bungeecord.git" }
# Programs
        - { source: "git@github.com:rick-gnous/Test-MSX.git", destination: "git@github.com:Bensuperpc/Test-MSX.git" }

    steps:
    - name: repo-sync
      uses: wei/git-sync@v3.0.0
      with:
        source_repo: ${{ matrix.repos_list.source }}
        source_branch: "refs/remotes/source/*"
        destination_repo: ${{ matrix.repos_list.destination }}
        destination_branch: "refs/remotes/source/*"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
